### ISSUE TITLE
Easybloqs suitable for original Arduino computers

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-webbased#104]
Webbased Leaphy easybloqs can not be used for original Arduino computers like nano every, would be nice to have this feature available

**Comment by koen1711** [comment]
#166

**Comment by koen1711** [comment]
The uploader itself has already been made, just needs an frontend for it.

**Comment by koen1711** [comment]
I think this can be marked as completed as we added a lot more robots, if we are missing any let us know and we will add those.
