### ISSUE TITLE
Uploaden geeft locking error na 1e upload

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-webbased#114]
Als ik in de blocks editor een eenvoudig programma upload (blink), krijg ik bij de 2e keer uploaden de volgende error in de console:

![Image](https://github.com/leaphy-robotics/leaphy-webbased/assets/8319432/46d23bf4-9a91-4f5a-916d-48282ef269b7)

Platform: linux (dus geen driver gedoe).

Programma:

![Image](https://github.com/leaphy-robotics/leaphy-webbased/assets/8319432/57fe9324-dc67-49ba-bb16-69cccdfa10fa)

Als ik F5 doe, weer Uno selecteer en dan upload, werkt het weer 1 keer, daarna dezelfde melding.

![Image](https://github.com/leaphy-robotics/leaphy-webbased/assets/8319432/4b406fdb-c5bf-4279-a807-3ab02591a67d)

**Comment by rmoesbergen** [comment]
@koen1711 dit gaat mis sinds de python editor, zie ook de melding over de chromebooks in whatsapp. Enig idee?

**Comment by rmoesbergen** [comment]
```
            upload(t, e=(i=>{}
            )) {
                var i = this;
                return Qt(function*() {
                    if (i.isUploading)
                        throw new Error("Arduino is already uploading");
                    let r;
                    i.robotWiredState.clearUploadLog(),
                    i.isUploading = !0,
                    i.readStream = i.port.readable.getReader(),
                    i.writeStream = i.port.writable.getWriter();
                    try {
```

Die i.port.readable.getReader() gooit deze error. Blijkbaar wordt de poort niet unlocked ergens.

**Comment by koen1711** [comment]
Hmmm, ik heb het vaker al zien langs komen maar het gebeurt soms wel soms niet zal er naar kijken.

**Comment by rmoesbergen** [comment]
> Hmmm, ik heb het vaker al zien langs komen maar het gebeurt soms wel soms niet zal er naar kijken.

oke, thanks. Ik kan het hier iig consistent reproduceren.

**Comment by koen1711** [comment]
fixed
