### ISSUE TITLE
Serial monitor uitbreiden met 'zend' mogelijkheid

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-webbased#121]
De serial monitor kan op dit moment alleen ontvangen. Zou heel gaaf zijn als je ook iets kunt zenden, net zoals dat met de arduino serial monitor kan. Hiervoor zijn dan ook blocks nodig om de arduino iets te laten ontvangen vanaf de serial poort. (de tegenhanger van "Toon op scherm")

**Comment by sverben** [comment]
implemented in https://github.com/leaphy-robotics/leaphy-webbased/pull/122
