### ISSUE TITLE
Create an offline version of leaphy-webbased

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-webbased#141]
For locations that don't have (fast) internet, it would be very nice to have an offline version of leaphy webbased. 
We can perform a build of webbased and run that in electron. Then bundle the backend for compilation, so we don't need separate code for the offline/online versions.

**Comment by sverben** [comment]
early version available on https://github.com/leaphy-robotics/leaphy-desktop
