### ISSUE TITLE
[bug] folders not created when setting up MicroPython robot

### ISSUE THREAD

**Issue by sverben** [leaphy-robotics/leaphy-webbased#148]
**Describe the bug**
When connecting a new MicroPython robot, the console throws an enoent error in the put function, this is caused by commit https://github.com/leaphy-robotics/leaphy-webbased/commit/3c1911e3ced0795e9b6844049da5844ec8cc3616#diff-3dd74d07a6511f87cf439279fd75273575e4fa009a22d30cbd301bba7acd358eL43
Previously we automatically created these folders, this has been removed

**To Reproduce**
Erase MicroPython robot's lib folder and connect to EasyBloqs. 

**Expected behavior**
Proper folder structure should be created automatically in the put function (why was this removed?)

**Comment by rmoesbergen** [comment]
fixed in #149
