### ISSUE TITLE
Bijwerken README met ontwikkel procedures

### ISSUE THREAD

**Issue by Vosjedev** [leaphy-robotics/leaphy-webbased#162]
Ik vond wat bugs tijdens de recordpoging afgelopen woensdag (28-2-24), en ik wil proberen die te patchen. In de readme staat dat je de development branch moet forken en dat pr's naar main/master worden geweigerd, maar er lijkt geen dev branch te zijn? Is dit een foutje?

**Comment by rmoesbergen** [comment]
Hoi @Vosjedev , Oei, de README lijkt wat verouderd op dit vlak. We zijn inmiddels overgestapt op het maken van een branch + PR voor elke bug/feature/etc. Ik zal de README aanpassen. Bedankt voor het melden!
