### ISSUE TITLE
Sommige popups zijn niet af te sluiten

### ISSUE THREAD

**Issue by Vosjedev** [leaphy-robotics/leaphy-webbased#163]
Popups als 'Upload failed' en 'No web serial supported' zijn niet af te sluiten, en je kan er alleen uit door te refreshen

Ik ben bezig dit te fixen in een fork, dus verder hoeft niemand hieraan te werken. Als ik klaar ben stuur ik een PR in.

**Comment by rmoesbergen** [comment]
Hoi @Vosjedev , bedankt! Deze bug kwam ik ook regelmatig tegen, erg vervelend. We gaan je PR bekijken...

**Comment by rmoesbergen** [comment]
PR #164

**Comment by koen1711** [comment]
From the PR I can see this issue is fixed, closing

**Comment by rmoesbergen** [comment]
> From the PR I can see this issue is fixed, closing

De pr is niet gemerged en gaat dat ook niet worden. De juiste fix wordt door Sverre gemaakt
