### ISSUE TITLE
Opgeslagen bestanden krijgen als extensie .ino

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-webbased#18]
... dit wekt de indruk dat deze in de Arduino IDE geladen kunnen worden (en gebeurt ook als er op dubbelklikt). Het zijn echter geen C source files,  maar workspace XML files. Misschien beter .leaphy noemen of iets dergelijks.

**Comment by koen1711** [comment]
Fixed, also added it so that if you are in Advanced mode it saves as actual arduino code.
