### ISSUE TITLE
[bug] CSV download only downloads one line of results

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-webbased#236]
**Describe the bug**
When downloading a CSV file in the serial monitor, the downloaded file only contains one line of the output instead of all the lines (or the last 100)

**Comment by rmoesbergen** [comment]
@Basie147 deze is het

**Comment by JeftadeGraaf** [comment]
I tried to recreate this bug. But could not. Could you give more detail?

**Comment by rmoesbergen** [comment]
Interesting... it work for me now as well. Guess there's no bug (anymore).
