### ISSUE TITLE
Driver2 installation failure

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-webbased#26]
Failure to install Windows driver 2

Open Leaphy excecutables zip file via https://github.com/leaphy-robotics/leaphy-webbased/archive/refs/heads/executables.zip

Unzip Installation  Windows driver 2

After clicking Install, installation will start initially but after a few seconds the message "driver installation error" will be given in the select INF window

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by koen1711** [comment]
This looks like the driver has a weird installation system, sadly there is no way for us to fix this, or we have to make the driver ourself.
