### ISSUE TITLE
Exportbutton - Serial monitor tot csv-file 

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-webbased#38]
Great tool for Science-education: Export log-file Serial monitor to .csv-file (excel-compatible)
Button could be placed alongside the bin-button.

**Comment by JeftadeGraaf** [comment]
Ik heb inmiddels de support toegevoegd, ik heb de knop maar toegevoegd bij de serial window. Leek me een betere plek.

issues?
- De file name is nu een altijd dezelfde naam
- Je kan nu nog downloaden ook al is er nog geen serial output
- Nog andere fouten gevonden?

**Comment by JeftadeGraaf** [comment]
![image](https://github.com/leaphy-robotics/leaphy-webbased/assets/91546552/fe5b0f7e-01b4-44b1-b8c5-b34c0a6a532d)
Bedoel je daarbij de waardes tussen de tijd en data in? Ik zie trouwens niet je voorstel voor een filename.

**Comment by rmoesbergen** [comment]
> ![image](https://private-user-images.githubusercontent.com/91546552/290917772-fe5b0f7e-01b4-44b1-b8c5-b34c0a6a532d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NzUyNDksIm5iZiI6MTcwMjY3NDk0OSwicGF0aCI6Ii85MTU0NjU1Mi8yOTA5MTc3NzItZmU1YjBmN2UtMDFiNC00NGIxLWI4YzUtYjM0YzBhNmE1MzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDIxMTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMzRmMmZmNTE0NWU4NTEyOWRhYzk1NmYzMjUzOTA2M2IwZjA2NWVmOWViZmQ1YmZlOWI1MGFkYzk5ZTQ3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7KZOzU_cFeSeVIXUud9rIhn09tuywRkSCemrsktpLt0) Bedoel je daarbij de waardes tussen de tijd en data in? Ik zie trouwens niet je voorstel voor een filename.

Nee, ik bedoel in de csv zit in de data kolom na elke regel een extra \n, want die wordt door de arduino meegestuurd.

De comments staan hier:
https://github.com/leaphy-robotics/leaphy-webbased/pull/98/files

**Comment by JeftadeGraaf** [comment]
Heb de \n gefixt. Zie nog steeds niet de comments. https://github.com/leaphy-robotics/leaphy-webbased/pull/98/files hier staan alleen de veranderde files, zonder comments

**Comment by rmoesbergen** [comment]
Hmm, apart, komt misschien omdat ik de PR geopend heb, en er zelf comments in heb gezet. Ik gooi ze wel hier:



![Image](https://github.com/leaphy-robotics/leaphy-webbased/assets/8319432/15686dca-8fbf-4dba-b95e-c77290d77d45)



![Image](https://github.com/leaphy-robotics/leaphy-webbased/assets/8319432/a228eae8-8d07-49de-827c-3a9ab5968a40)

**Comment by rmoesbergen** [comment]
Misschien beter als jij een PR opent voor die branch. Zowieso wel handig, anders staat ie op mijn naam.

**Comment by JeftadeGraaf** [comment]
yes, gefixt. nu heb PR aangemaakt

**Comment by rmoesbergen** [comment]
👍  wat mij betreft kan deze gemerged!
