### ISSUE TITLE
Uitschuif window van C code atandaard uitzetten in alle omgevingen (knop behouden)

### ISSUE THREAD

**Issue by koen1711** [leaphy-robotics/leaphy-webbased#49]

**Comment by JeftadeGraaf** [comment]
Fixed in development branche, can be opened again if not working.

**Comment by rmoesbergen** [comment]
Ik heb het getest, maar het was juist de bedoeling dat het code window niet meer standaard uitgeschoven werd. Het lijkt er nu op dat het juist altijd wel gebeurt. Ik heb een fix gepushed.

**Comment by rmoesbergen** [comment]
released in 1.5.3
