### ISSUE TITLE
Bij opslaan als window een 'save' en 'cancel' knop toevoegen

### ISSUE THREAD

**Issue by JeftadeGraaf** [leaphy-robotics/leaphy-webbased#50]

**Comment by JeftadeGraaf** [comment]
Heb geprobeerd om de dialog te closen maar is niet gelukt, wil iemand anders hier nog even naar kijken?

**Comment by rmoesbergen** [comment]
Getest en werkt. Styling van de knoppen is nog een beetje meh, maar wel te doen.
