### ISSUE TITLE
Webbased updaten naar Angular 16 (met vite?)

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-webbased#63]
We zitten nu angular 15, de laatste versie 16. Volgens mij is dat ook geswitched naar vite ipv. webpack, maar even checken. Zou mooi zijn want is 100 keer sneller.

**Comment by koen1711** [comment]
Too much work too fix, and will need to remake basically everything

**Comment by koen1711** [comment]
Too much work too fix, and will need to remake basically everything
