### ISSUE TITLE
Pins aanpassen voor motorshield commandoblock met nano

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-webbased#69]

**Comment by rmoesbergen** [comment]
![Image](https://github.com/leaphy-robotics/leaphy-webbased/assets/8319432/c57b13d9-dc2a-49b8-9687-f30f48f2af40)

**Comment by rmoesbergen** [comment]
De pin layout is anders dan voor het L293P shield. Zie screenshot voor de goede layout. Let op: dit is dus alleen voor de nano motorshield, het origineel moet blijven zoals het nu is.

**Comment by rmoesbergen** [comment]
@beekumo De huidige shield heeft de volgende pin layout:
```
// PIN definitions for Fundumoto L298P motor shield with built in buzzer
#define M1_PWM          (10)    // Motor A PWM
#define M1_DIR          (12)    // Motor A direction
#define M2_PWM          (11)    // Motor B PWM
#define M2_DIR          (13)    // Motor B direction
#define TONE_PIN        (4)     // DIG-OUT
#define LED1_RED        (6)     // PWM-OUT
#define LED1_GREEN      (5)     // PWM-OUT
#define LED1_BLUE       (3)     // PWM-OUT
#define LINE_LEFT       (16)    // DIG-IN       A2 tinkerkit In2
#define LINE_RIGHT      (17)    // DIG-IN       A3 tinkerkit In3
#define US_ECHO         (8)     // DIG-IN/OUT
#define US_TRIG         (7)     // DIG-OUT
```

Hoe ziet de nieuwe layout eruit? Uit de screenshot kan ik niet goed opmaken welke pins er nu anders zijn.

**Comment by beekumo** [comment]
@rmoesbergen hierbij de layout voor het nieuwe motor shield, alleen voor in Flitz nano en Leaphy original nano omgeving(!)

#define M1_PWM          (3)    // Motor A PWM
#define M1_DIR          (2)    // Motor A direction
#define M2_PWM          (11)    // Motor B PWM
#define M2_DIR          (4)    // Motor B direction

**Comment by rmoesbergen** [comment]
Aangepast en gereleased in 1.7.0.
