### ISSUE TITLE
Gnd Neuslampje Fltz nano

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-webbased#72]
Commandoblok neuslampje (RGB les) voor de Fliz nano heeft geen annotatie voor de Gnd pin waardoor dit blok niet werkt. De Gnd van het neuslampje zit bij volgen van de reguliere montage instructie aan digitale pin 8. Deze graag op low zetten in het commandoblok voor neuslampje.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rmoesbergen** [comment]
opgelost
